global:
  external_labels:
      monitor: 'codelab-monitor'
rule_files:
  - /etc/prometheus/rules/*.rules
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.29.132:9090']
  - job_name: 'linux'
    static_configs:
      - targets: ['192.168.29.132:9100','192.168.29.133:9100']
        labels:
          instance: ansible
  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.29.133:9104']
        labels:
          instance: db1
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['192.168.29.132:9093']